---
title: "BYU-I career fair data"
author: "Dongchan Lim"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    theme: cerulean 
    keep_md: true
    toc: true
    toc_float: true
    code_folding: hide
    fig_height: 6
    fig_width: 12
    fig_align: 'center'
---

```{r, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r load_libraries, include=FALSE}
# Use this R-Chunk to load all your libraries!
#install.packages("tidyverse") # run this line once in console to get package
library(tidyverse)
library(readr)
library(pander)
```

```{r load_data}
# Use this R-Chunk to import all your datasets!
careerfair <- read_csv("BYUI_FallCareerFair.csv")
```

## Background

This is a summary of BYU-I career fair data

## Data Wrangling

```{r tidy_data}
# Use this R-Chunk to clean & wrangle your data!
careerfair %>% glimpse() %>% pander()
```

## Data Visualization

```{r plot_data}
# Use this R-Chunk to plot & visualize your data!
careerfair_1 <- careerfair %>% mutate(State = as.factor(toupper(State)), City =  as.factor(tolower(City))) %>% filter(`Organization Type` == 'Employer', !is.na(State), !is.na(City), State %in% c('ID','UT'))

careerfair_1 %>% ggplot() + geom_bar(aes(x = City, fill = City), width = 0.5)  + theme_bw() + theme(legend.position = "none", axis.text.x = element_text(angle = 90, hjust = 1)) 
```

## Conclusions
